repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        name: ruff check and fix
        args: [check, --select, I, --fix, .]
      
      - id: ruff-format
        name: ruff format
        args: [.]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
     - id: mypy
       args: [--config-file=pyproject.toml]
       additional_dependencies:
        - pydantic>=2.0.0
        - types-setuptools
        - types-requests